services:
  events_node_db:
    restart: always
    image: postgres:16-alpine
    container_name: events_node_db
    env_file:
        - path: ./.env
    ports:
      - "$POSTGRES_PORT:5432"


# todo: сделать полный запуск проекта с помощью  docker-compose, а не только БД